<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.technic47</groupId>
        <artifactId>shop-spring-boot-starter</artifactId>
        <version>1.1.13</version>
    </parent>

    <artifactId>store</artifactId>
    <version>1.1.3</version>
    <name>Store_module</name>
    <description>Store_module</description>

    <properties>
        <skipTests>true</skipTests>
        <app.main-class>ru.kuznetsov.shop.store.ShopStoreModuleApplication</app.main-class>
        <app.build-finalName>Store_module</app.build-finalName>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.technic47</groupId>
            <artifactId>data-model</artifactId>
            <version>${data-model.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.technic47</groupId>
            <artifactId>parameter</artifactId>
            <version>${parameter-access.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>compose</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <finalName>${app.build-finalName}</finalName>
            </build>
        </profile>
        <profile>
            <id>k8s</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>${apache.maven-jar-plugin.version}</version>
                        <configuration>
                            <archive>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                    <mainClass>
                                        ${app.main-class}
                                    </mainClass>
                                </manifest>
                            </archive>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>io.fabric8</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <version>${io.fabric8.docker-maven-plugin.version}</version>
                        <executions>
                            <execution>
                                <id>Build docker container</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>Push docker container</id>
                                <phase>deploy</phase>
                                <goals>
                                    <goal>push</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <images>
                                <image>
                                    <name>${project.artifactId}</name>
                                    <build>
                                        <from>eclipse-temurin:21-jre-alpine</from>
                                        <tags>
                                            <tag>${project.version}</tag>
                                        </tags>
                                        <entryPoint>
                                            <exec>
                                                <arg>java</arg>
                                                <arg>-jar</arg>
                                                <arg>jars/${project.build.finalName}.jar</arg>
                                            </exec>
                                        </entryPoint>
                                        <assembly>
                                            <basedir>/</basedir>
                                            <inline>
                                                <dependencySet>
                                                    <outputDirectory>jars</outputDirectory>
                                                </dependencySet>
                                                <files>
                                                    <file>
                                                        <source>${project.build.directory}/${project.build.finalName}.jar
                                                        </source>
                                                        <outputDirectory>jars</outputDirectory>
                                                    </file>
                                                    <file>
                                                        <source>${project.basedir}/src/main/resources/application.yml</source>
                                                        <outputDirectory>/</outputDirectory>
                                                    </file>
                                                </files>
                                            </inline>
                                        </assembly>
                                    </build>
                                </image>
                            </images>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
