spring:
  application:
    name: Shop_store_module

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    generate-ddl: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: ${STORE_GROUP_ID}